"""Create generic source provenance and canonical railway segments.

Revision ID: 0001_railway_domain
Revises:
"""

from alembic import op

revision = "0001_railway_domain"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE public.data_sources (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            slug text NOT NULL UNIQUE,
            name text NOT NULL,
            publisher text NOT NULL,
            url text NOT NULL,
            license text NOT NULL,
            snapshot_at timestamptz,
            retrieved_at timestamptz NOT NULL,
            description text
        )
    """)
    op.execute("""
        CREATE TABLE public.railway_segments (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_id bigint NOT NULL REFERENCES public.data_sources(id),
            source_object_type text NOT NULL,
            source_object_id bigint NOT NULL,
            name text,
            ref text,
            railway_type text NOT NULL CHECK (railway_type IN ('rail', 'narrow_gauge')),
            usage text,
            service text,
            operator text,
            electrified text,
            gauge text,
            tracks text,
            maxspeed text,
            bridge text,
            tunnel text,
            status text NOT NULL DEFAULT 'active' CHECK (status = 'active'),
            geom geometry(LineString, 4326) NOT NULL,
            CONSTRAINT railway_segments_source_object_key
                UNIQUE (source_id, source_object_type, source_object_id),
            CONSTRAINT railway_segments_valid_geom
                CHECK (NOT ST_IsEmpty(geom) AND ST_IsValid(geom) AND ST_NPoints(geom) >= 2)
        )
    """)
    op.execute("CREATE INDEX railway_segments_geom_gix ON public.railway_segments USING GIST (geom)")


def downgrade() -> None:
    op.execute("DROP TABLE public.railway_segments")
    op.execute("DROP TABLE public.data_sources")
