"""Create canonical major roads and zoom-aware MVT delivery.

Revision ID: 0004_road_domain
Revises: 0003_railway_mvt_buffer
"""

from alembic import op


revision = "0004_road_domain"
down_revision = "0003_railway_mvt_buffer"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE public.road_segments (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_id bigint NOT NULL REFERENCES public.data_sources(id),
            source_object_type text NOT NULL CHECK (source_object_type = 'way'),
            source_object_id bigint NOT NULL,
            name text,
            ref text,
            road_class text NOT NULL CHECK (road_class IN
                ('motorway', 'trunk', 'primary', 'secondary', 'tertiary')),
            is_link boolean NOT NULL,
            surface text,
            lanes text,
            maxspeed text,
            oneway text,
            access text,
            toll text,
            bridge text,
            tunnel text,
            operator text,
            network text,
            status text NOT NULL DEFAULT 'active' CHECK (status = 'active'),
            geom geometry(LineString, 4326) NOT NULL,
            CONSTRAINT road_segments_source_object_key
                UNIQUE (source_id, source_object_type, source_object_id),
            CONSTRAINT road_segments_valid_geom
                CHECK (NOT ST_IsEmpty(geom) AND ST_IsValid(geom) AND ST_NPoints(geom) >= 2)
        )
    """)
    op.execute("CREATE INDEX road_segments_geom_gix ON public.road_segments USING GIST (geom)")
    op.execute("""
        CREATE FUNCTION public.road_segments_mvt(z integer, x integer, y integer)
        RETURNS bytea
        LANGUAGE plpgsql STABLE STRICT PARALLEL SAFE
        AS $function$
        DECLARE
            tile_bounds geometry;
            query_bounds geometry;
            tile_bytes bytea;
        BEGIN
            IF z < 5 THEN
                RETURN '\\x'::bytea;
            END IF;

            tile_bounds := ST_TileEnvelope(z, x, y);
            query_bounds := ST_TileEnvelope(z, x, y, margin => 64.0 / 4096.0);
            SELECT ST_AsMVT(tile, 'road_segments', 4096, 'geom', 'id')
            INTO tile_bytes
            FROM (
                SELECT
                    r.id, r.name, r.ref, r.road_class, r.is_link, r.surface,
                    r.lanes, r.maxspeed, r.oneway, r.access, r.toll, r.bridge,
                    r.tunnel, r.operator, r.network,
                    ST_AsMVTGeom(
                        ST_Transform(r.geom, 3857), tile_bounds, 4096, 64, true
                    ) AS geom
                FROM public.road_segments AS r
                WHERE r.geom && ST_Transform(query_bounds, 4326)
                  AND (z >= 10 OR (
                      NOT r.is_link AND (
                          r.road_class IN ('motorway', 'trunk')
                          OR (z >= 6 AND r.road_class = 'primary')
                          OR (z >= 7 AND r.road_class = 'secondary')
                          OR (z >= 8 AND r.road_class = 'tertiary')
                      )
                  ))
            ) AS tile
            WHERE tile.geom IS NOT NULL;

            RETURN COALESCE(tile_bytes, '\\x'::bytea);
        END;
        $function$
    """)
    op.execute("""
        COMMENT ON FUNCTION public.road_segments_mvt(integer, integer, integer) IS
        '{
          "description": "Major OSM road segments with semantic zoom visibility",
          "minzoom": 5,
          "maxzoom": 14,
          "attribution": "© OpenStreetMap contributors",
          "vector_layers": [{
            "id": "road_segments",
            "fields": {
              "name": "String", "ref": "String", "road_class": "String",
              "is_link": "Boolean", "surface": "String", "lanes": "String",
              "maxspeed": "String", "oneway": "String", "access": "String",
              "toll": "String", "bridge": "String", "tunnel": "String",
              "operator": "String", "network": "String"
            }
          }]
        }'
    """)


def downgrade() -> None:
    op.execute("DROP FUNCTION public.road_segments_mvt(integer, integer, integer)")
    op.execute("DROP TABLE public.road_segments")
