"""Create canonical civilian port points and their vector tile source.

Revision ID: 0006_port_domain
Revises: 0005_road_mvt_aggregation
"""

from alembic import op


revision = "0006_port_domain"
down_revision = "0005_road_mvt_aggregation"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE public.ports (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_id bigint NOT NULL REFERENCES public.data_sources(id),
            source_object_type text NOT NULL CHECK (source_object_type IN ('node', 'way', 'relation')),
            source_object_id bigint NOT NULL,
            name text,
            name_en text,
            facility_class text NOT NULL CHECK (facility_class IN
                ('commercial_port', 'cargo_terminal', 'fishing_port', 'port')),
            water_context text CHECK (water_context IN ('sea', 'river', 'lake')),
            cargo text,
            operator text,
            owner text,
            website text,
            wikidata text,
            wikipedia text,
            access text,
            status text NOT NULL DEFAULT 'active' CHECK (status = 'active'),
            geom geometry(Point, 4326) NOT NULL,
            CONSTRAINT ports_source_object_key UNIQUE
                (source_id, source_object_type, source_object_id),
            CONSTRAINT ports_valid_geom CHECK (NOT ST_IsEmpty(geom) AND ST_IsValid(geom))
        )
    """)
    op.execute("CREATE INDEX ports_geom_gix ON public.ports USING GIST (geom)")
    op.execute(r"""
        CREATE FUNCTION public.ports_mvt(z integer, x integer, y integer)
        RETURNS bytea
        LANGUAGE plpgsql STABLE STRICT PARALLEL SAFE
        AS $function$
        DECLARE
            tile_bounds geometry;
            query_bounds geometry;
            tile_bytes bytea;
        BEGIN
            IF z < 5 THEN
                RETURN '\x'::bytea;
            END IF;

            tile_bounds := ST_TileEnvelope(z, x, y);
            query_bounds := ST_TileEnvelope(z, x, y, margin => 64.0 / 4096.0);
            SELECT ST_AsMVT(tile, 'ports', 4096, 'geom', 'id') INTO tile_bytes
            FROM (
                SELECT p.id, p.name, p.facility_class, p.water_context,
                    p.cargo, p.operator, p.access, p.status,
                    ST_AsMVTGeom(ST_Transform(p.geom, 3857),
                        tile_bounds, 4096, 64, true) AS geom
                FROM public.ports AS p
                WHERE p.geom && ST_Transform(query_bounds, 4326)
                  AND (z >= 7 OR NULLIF(btrim(p.name), '') IS NOT NULL)
            ) AS tile
            WHERE tile.geom IS NOT NULL;

            RETURN COALESCE(tile_bytes, '\x'::bytea);
        END;
        $function$
    """)
    op.execute("""
        COMMENT ON FUNCTION public.ports_mvt(integer, integer, integer) IS
        '{
          "description": "Civilian port facilities; named at z5-z6, all from z7",
          "minzoom": 5,
          "maxzoom": 14,
          "attribution": "© OpenStreetMap contributors",
          "vector_layers": [{
            "id": "ports",
            "fields": {
              "name": "String", "facility_class": "String",
              "water_context": "String", "cargo": "String",
              "operator": "String", "access": "String", "status": "String"
            }
          }]
        }'
    """)


def downgrade() -> None:
    op.execute("DROP FUNCTION public.ports_mvt(integer, integer, integer)")
    op.execute("DROP TABLE public.ports")
