"""Create canonical waterway centerline segments and Martin MVT function.

Revision ID: 0007_waterway_domain
Revises: 0006_port_domain
"""

from alembic import op


revision = "0007_waterway_domain"
down_revision = "0006_port_domain"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE public.waterway_segments (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_id bigint NOT NULL REFERENCES public.data_sources(id),
            source_object_type text NOT NULL CHECK (source_object_type = 'way'),
            source_object_id bigint NOT NULL,
            name text,
            name_en text,
            ref text,
            waterway_class text NOT NULL CHECK (waterway_class IN ('river', 'canal', 'fairway')),
            boat_access text,
            motorboat_access text,
            ship_access text,
            oneway_boat text,
            cemt_class text,
            usage text,
            service text,
            width text,
            intermittent boolean,
            tidal boolean,
            operator text,
            wikidata text,
            wikipedia text,
            status text NOT NULL DEFAULT 'active' CHECK (status = 'active'),
            geom geometry(LineString, 4326) NOT NULL,
            CONSTRAINT waterway_segments_source_object_key
                UNIQUE (source_id, source_object_type, source_object_id),
            CONSTRAINT waterway_segments_valid_geom
                CHECK (NOT ST_IsEmpty(geom) AND ST_IsValid(geom) AND ST_NPoints(geom) >= 2)
        )
    """)
    op.execute("CREATE INDEX waterway_segments_geom_gix ON public.waterway_segments USING GIST (geom)")
    op.execute(r"""
        CREATE FUNCTION public.waterway_segments_mvt(z integer, x integer, y integer)
        RETURNS bytea
        LANGUAGE plpgsql STABLE STRICT PARALLEL SAFE
        AS $function$
        DECLARE
            tile_bounds geometry;
            query_bounds geometry;
            tile_bytes bytea;
        BEGIN
            IF z < 5 THEN
                RETURN '\x'::bytea;
            END IF;

            tile_bounds := ST_TileEnvelope(z, x, y);
            query_bounds := ST_TileEnvelope(z, x, y, margin => 64.0 / 4096.0);
            SELECT ST_AsMVT(tile, 'waterway_segments', 4096, 'geom', 'id')
            INTO tile_bytes
            FROM (
                SELECT w.id, w.name, w.ref, w.waterway_class,
                    w.boat_access, w.motorboat_access, w.ship_access,
                    w.oneway_boat, w.cemt_class, w.usage, w.intermittent, w.tidal,
                    ST_AsMVTGeom(ST_Transform(w.geom, 3857),
                        tile_bounds, 4096, 64, true) AS geom
                FROM public.waterway_segments AS w
                WHERE w.geom && ST_Transform(query_bounds, 4326)
            ) AS tile
            WHERE tile.geom IS NOT NULL;

            RETURN COALESCE(tile_bytes, '\x'::bytea);
        END;
        $function$
    """)
    op.execute("""
        COMMENT ON FUNCTION public.waterway_segments_mvt(integer, integer, integer) IS
        '{
          "description": "OSM river, canal, and fairway centerline ways; navigation is not inferred",
          "minzoom": 5,
          "maxzoom": 14,
          "attribution": "© OpenStreetMap contributors",
          "vector_layers": [{
            "id": "waterway_segments",
            "fields": {
              "name": "String", "ref": "String", "waterway_class": "String",
              "boat_access": "String", "motorboat_access": "String",
              "ship_access": "String", "oneway_boat": "String",
              "cemt_class": "String", "usage": "String",
              "intermittent": "Boolean", "tidal": "Boolean"
            }
          }]
        }'
    """)


def downgrade() -> None:
    op.execute("DROP FUNCTION public.waterway_segments_mvt(integer, integer, integer)")
    op.execute("DROP TABLE public.waterway_segments")
